platform :ios,'13.0'

inhibit_all_warnings!

#source 'https://github.com/CocoaPods/Specs.git'

target 'SmartBenefitWhale' do
	pod 'AFNetworking'
	pod 'MBProgressHUD'
	pod 'SDWebImage'
  pod 'Masonry'
  
#  pod 'AMap3DMap-NO-IDFA'
#  pod 'AMapSearch-NO-IDFA'
#  pod 'AMapLocation-NO-IDFA'
  
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
        end
    end
end
